import SwiftData
import XCTest
@testable import PomoGem

@MainActor
final class CloudSchemaCompatibilityTests: XCTestCase {
    /// Validate the expanded runtime schema, including defaults generated by
    /// @Model. A local-only container can accept fields that CloudKit rejects.
    func testCloudAttributesSupportPartialCloudKitRecords() {
        let schema = PersistenceStoreTopology.cloudSchema
        XCTAssertFalse(schema.entities.isEmpty)
        for entity in schema.entities {
            XCTAssertTrue(
                entity.uniquenessConstraints.isEmpty,
                "CloudKit cannot enforce uniqueness for \(entity.name)"
            )
            for attribute in entity.attributes {
                XCTAssertTrue(
                    attribute.isOptional || attribute.defaultValue != nil,
                    "\(entity.name).\(attribute.name) needs a default or optional value"
                )
            }
        }
    }

    func testCloudRelationshipsAreOptionalAndStayInTheCloudStore() throws {
        let schema = PersistenceStoreTopology.cloudSchema
        let projectionNames = Set(
            PersistenceStoreTopology.localProjectionSchema.entities.map(\.name)
        )
        XCTAssertTrue(Set(schema.entities.map(\.name)).isDisjoint(with: projectionNames))
        for entity in schema.entities {
            for relationship in entity.relationships {
                let label = "\(entity.name).\(relationship.name)"
                XCTAssertTrue(relationship.isOptional, label)
                XCTAssertNotEqual(relationship.deleteRule, .deny, label)
                let destination = try XCTUnwrap(
                    schema.entitiesByName[relationship.destination], label
                )
                let inverseName = try XCTUnwrap(relationship.inverseName, label)
                let inverse = try XCTUnwrap(
                    destination.relationshipsByName[inverseName], label
                )
                XCTAssertEqual(inverse.destination, entity.name, label)
                XCTAssertEqual(inverse.inverseName, relationship.name, label)
            }
        }
    }
}
